/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: BeeKING (https://sketchfab.com/bahoduroviskandar51)
License: SKETCHFAB Standard (https://sketchfab.com/licenses)
Source: https://sketchfab.com/3d-models/coconut-shampoo-with-moisturizing-oils-7cb5c68fc663488c9c4131eb7201b5c7
Title: Coconut Shampoo with Moisturizing Oils
*/

import * as THREE from "three";
import { useRef, type JSX } from "react";
import { useGLTF } from "@react-three/drei";
import { useFrame } from "@react-three/fiber";
import { type Mesh } from "three";

export default function Model(props: Readonly<JSX.IntrinsicElements["group"]>) {
  const { nodes, materials } = useGLTF("/models/shampoo.gltf");
  const groupRef = useRef<THREE.Group>(null);
  useFrame((_state, delta) => {
    groupRef.current?.rotateY(delta);
  });
  return (
    <group {...props} dispose={null} ref={groupRef}>
      <group>
        <group rotation={[-Math.PI / 2, 0, 0]}>
          <group>
            <group rotation={[Math.PI / 2, 0, 0]}>
              <group>
                <mesh
                  castShadow
                  receiveShadow
                  geometry={(nodes.Object_4 as Mesh).geometry}
                  material={materials["Material.007"]}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={(nodes.Object_5 as Mesh).geometry}
                  material={materials["Material.002"]}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={(nodes.Object_6 as Mesh).geometry}
                  material={materials["Material.003"]}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={(nodes.Object_7 as Mesh).geometry}
                  material={materials.Cheap_Plastic}
                />
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/models/shampoo.gltf");
