/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: BeeKING (https://sketchfab.com/bahoduroviskandar51)
License: SKETCHFAB Standard (https://sketchfab.com/licenses)
Source: https://sketchfab.com/3d-models/coconut-shampoo-with-moisturizing-oils-7cb5c68fc663488c9c4131eb7201b5c7
Title: Coconut Shampoo with Moisturizing Oils
*/

import * as THREE from "three";
import { useRef, type JSX } from "react";
import { ContactShadows, Float, Plane, useGLTF } from "@react-three/drei";
import { type GLTF } from "three-stdlib";
import { useFrame } from "@react-three/fiber";

type GLTFResult = GLTF & {
  nodes: {
    Object_4: THREE.Mesh;
    Object_5: THREE.Mesh;
    Object_6: THREE.Mesh;
    Object_7: THREE.Mesh;
  };
  materials: {
    ["Material.007"]: THREE.MeshStandardMaterial;
    ["Material.002"]: THREE.MeshStandardMaterial;
    ["Material.003"]: THREE.MeshPhysicalMaterial;
    Cheap_Plastic: THREE.MeshPhysicalMaterial;
  };
};

export default function Model(props: Readonly<JSX.IntrinsicElements["group"]>) {
  const { nodes, materials } = useGLTF("/models/shampoo.gltf");
  const groupRef = useRef<THREE.Group>(null);
  useFrame((_state, delta) => {
    groupRef.current?.rotateY(delta);
  });
  return (
    <group {...props} dispose={null} ref={groupRef}>
      <group>
        <group rotation={[-Math.PI / 2, 0, 0]}>
          <group>
            <group rotation={[Math.PI / 2, 0, 0]}>
              <group>
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_4.geometry}
                  material={materials["Material.007"]}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_5.geometry}
                  material={materials["Material.002"]}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_6.geometry}
                  material={materials["Material.003"]}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_7.geometry}
                  material={materials.Cheap_Plastic}
                />
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/models/shampoo.gltf");
